#ifndef MODEMCONNECTIONMANAGER_GLOBAL_H
#define MODEMCONNECTIONMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODEMCONNECTIONMANAGER_LIBRARY)
#define MODEMCONNECTIONMANAGER_EXPORT Q_DECL_EXPORT
#else
#define MODEMCONNECTIONMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // MODEMCONNECTIONMANAGER_GLOBAL_H
